In [1]:
import numpy as np
from tqdm import tqdm
import pandas as pd
from sklearn import svm,preprocessing
from sklearn.linear_model import LogisticRegression,LinearRegression,BayesianRidge,Ridge,Lasso,MultiTaskLasso,ElasticNet,LassoLars
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier,RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt


TEST_DIR=""
df=pd.read_csv(r'C:\Users\My PC\Desktop\Machine Learning\Hackerearth\Employeechurn\train.csv')
#print(df.head())

def check_broken_values(df):
	#print(df.columns)
	columns=[]
	empty=[]
	columns=df.columns
	#print(columns)
	for feature in columns:
		for rows in df[feature]:
			if pd.isna(rows)==True:
				#print(feature,"NULL_VAL_FOUND")
				empty.append(feature)
				break
				
	return empty

def fix_broken_values(df):

	empty_columns=check_broken_values(df)
	#print(empty_columns)
	for col in empty_columns:
		#print(col,np.mean(df[col]))
		df[col].fillna(np.mean(df[col]),inplace=True)
	
	#df.to_csv('final.csv',index=False)
	return df


def handle_non_numeric_data(df):
	columns=df.columns.values
	print(columns)
	for column in columns:
		text_digit_vals={}
		def convert_to_int(val):
			return text_digit_vals[val]
		if df[column].dtype!=np.int64 and df[column].dtype!=np.float64:
			column_contents=df[column].values.tolist()
			unique_elements=set(column_contents)

			x=0
			for unique in unique_elements:
				if unique not in text_digit_vals:
					text_digit_vals[unique]=x
					x+=1
			df[column]=list(map(convert_to_int,df[column]))
	#df.to_csv('finale.csv',index=False)
	return df


#df1=fix_broken_values(df)
#print(check_broken_values(df1))
#df1=handle_non_numeric_data(df1)
#print(df1.head())

#df=pd.read_csv('finale.csv')
#print(df.head())
#df=pd.read_csv(TRAIN_DIR)
df=fix_broken_values(df)
df=handle_non_numeric_data(df)
df.drop(['Employee_ID'],1,inplace=True)
x=np.array(df.drop(['Attrition_rate'],1).astype(float))
#x=preprocessing.scale(x)
print(x)
y=np.array(df.Attrition_rate)
clf=GradientBoostingRegressor()
# train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.3,random_state=1993)














# plot feature importance

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
clf.fit(x_train,y_train)
'''print(clf.feature_importances_)
plot_importance(clf)'''
#print(x)
#plt.show()
accuracy=clf.score(x_test,y_test)
print(accuracy)
predict_me=np.array([1,42.0,4,1,4,5,1,4.0,4,33,1,1,7.0,4,3.0,4,0.7516,1.8688,2.0,4,5,3])
predict_me=predict_me.reshape(-1,len(predict_me))
#print(clf.predict(predict_me))
df4=pd.read_csv(r'C:\Users\My PC\Desktop\Machine Learning\Hackerearth\Employeechurn\test.csv')
df3=pd.read_csv(r'C:\Users\My PC\Desktop\Machine Learning\Hackerearth\Employeechurn\test.csv')
#print(df2.head())
with open(r'C:\Users\My PC\Desktop\Machine Learning\Hackerearth\Employeechurn\sub.csv','w') as f:
	f.write('Employee_ID,Attrition_rate\n')
df2=fix_broken_values(df3)
df2=handle_non_numeric_data(df2)


for count,rows in enumerate(df2.Age):
	predict_me=np.array([df2.Gender[count],df2.Age[count],df2.Education_Level[count],df2.Relationship_Status[count],df2.Hometown[count],df2.Unit[count],df2.Decision_skill_possess[count],df2.Time_of_service[count],df2.Time_since_promotion[count],df2.growth_rate[count],df2.Travel_Rate[count],df2.Post_Level[count],df2.Pay_Scale[count],df2.Compensation_and_Benefits[count],df2.Work_Life_balance[count],df2.VAR1[count],df2.VAR2[count],df2.VAR3[count],df2.VAR4[count],df2.VAR5[count],df2.VAR6[count],df2.VAR7[count]])
	predict_me=predict_me.reshape(-1,len(predict_me))
		#print(clf.predict(predict_me))
	with open(r'C:\Users\My PC\Desktop\Machine Learning\Hackerearth\Employeechurn\sub.csv','a') as f:
		f.write("{},{}\n".format(df4.Employee_ID[count],clf.predict(predict_me)[0]))

['Employee_ID' 'Gender' 'Age' 'Education_Level' 'Relationship_Status'
 'Hometown' 'Unit' 'Decision_skill_possess' 'Time_of_service'
 'Time_since_promotion' 'growth_rate' 'Travel_Rate' 'Post_Level'
 'Pay_Scale' 'Compensation_and_Benefits' 'Work_Life_balance' 'VAR1' 'VAR2'
 'VAR3' 'VAR4' 'VAR5' 'VAR6' 'VAR7' 'Attrition_rate']
[[ 1. 42.  4. ...  4.  5.  3.]
 [ 0. 24.  3. ...  3.  5.  3.]
 [ 1. 58.  3. ...  3.  8.  3.]
 ...
 [ 1. 49.  3. ...  4.  8.  3.]
 [ 1. 47.  3. ...  3.  6.  3.]
 [ 1. 58.  3. ...  4.  5.  3.]]
-0.010827050441563513
['Employee_ID' 'Gender' 'Age' 'Education_Level' 'Relationship_Status'
 'Hometown' 'Unit' 'Decision_skill_possess' 'Time_of_service'
 'Time_since_promotion' 'growth_rate' 'Travel_Rate' 'Post_Level'
 'Pay_Scale' 'Compensation_and_Benefits' 'Work_Life_balance' 'VAR1' 'VAR2'
 'VAR3' 'VAR4' 'VAR5' 'VAR6' 'VAR7']

In [98]:

df2.head()

,Employee_ID,Gender,Age,Education_Level,Relationship_Status,Hometown,Unit,Decision_skill_possess,Time_of_service,Time_since_promotion,growth_rate,Travel_Rate,Post_Level,Pay_Scale,Compensation_and_Benefits,Work_Life_balance,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7
0,1356,0,32.0,5,0,4,0,3,7.0,4,30,1,5,4.0,1,1.0,3,-0.9612,-0.4537,2.0,1,8,4
1,2854,1,65.0,2,0,0,7,2,41.0,2,72,1,1,1.0,1,1.0,4,-0.9612,0.7075,1.0,2,8,2
2,2196,1,52.0,3,1,4,10,2,21.0,3,25,0,1,8.0,3,1.0,4,-0.1048,0.7075,2.0,1,9,3
3,560,1,50.0,5,0,2,4,0,11.0,4,28,1,1,2.0,4,4.0,3,-0.1048,0.7075,2.0,2,8,3
4,2456,0,44.0,3,1,3,0,3,12.0,4,47,1,3,2.0,1,4.0,4,1.6081,0.7075,2.0,2,7,4

In [96]:
Id

0       1356
1       2854
2       2196
3        560
4       2456
5       2386
6       1624
7       2218
8       2417
9       1919
10       776
11      2206
12      2930
13      2846
14       637
15      2394
16      1259
17      2071
18       213
19       215
20      1049
21       717
22       174
23      2613
24      2600
25      2766
26      1910
27      2722
28      1999
29      2738
        ...
2970    1319
2971    2432
2972     225
2973    2783
2974    2183
2975    1387
2976    2690
2977    2202
2978    1003
2979      82
2980     944
2981    2972
2982     952
2983    1329
2984    1372
2985    2997
2986    2293
2987     609
2988     849
2989     335
2990     273
2991     235
2992    2492
2993     877
2994    2208
2995    2667
2996     151
2997    2755
2998    1449
2999    2777
Name: Employee_ID, Length: 3000, dtype: int64